# Generated by Django 6.0 on 2026-09-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
