# Generated by Django 6.0 on 2026-09-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_remove_article_published_remove_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='myfile',
        ),
    ]
