# Generated by Django 6.0 on 2026-09-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_remove_article_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='whatsapp',
        ),
    ]
