# Generated by Django 6.0 on 2026-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_footer_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=30)),
                ('linkdin', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=30)),
            ],
        ),
    ]
