# Generated by Django 6.0 on 2026-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_aboutlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlinks',
            name='github',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutlinks',
            name='instagram',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutlinks',
            name='linkdin',
            field=models.CharField(max_length=50),
        ),
    ]
