# Generated by Django 6.0 on 2026-09-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_aboutlinks_github_alter_aboutlinks_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutlinks',
            old_name='linkdin',
            new_name='linkedin',
        ),
    ]
